on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy the new website
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          WORKDIR: ${{ secrets.WORKDIR }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
          ssh root@$SERVER_IP "cd $WORKDIR && git pull origin master"
          ssh root@$SERVER_IP "cd $WORKDIR && docker compose build"
          ssh root@$SERVER_IP "cd $WORKDIR && docker compose up --force-recreate -d"
